### ISSUE TITLE
Random hash at the end of curriculum README

### ISSUE THREAD

**Issue by pcatana** [HackYourFuture-CPH/curriculum#1]
Hi!
I've noticed this random hash at the end of the curriculum [readme](https://github.com/HackYourFuture-CPH/curriculum#curriculum)  
Is there any purpose for this?

**Comment by chklueter** [comment]
Yea, should probably get removed. No clue how it ended up there in the first place

**Comment by pcatana** [comment]
Ok. Will remove it.
