### ISSUE TITLE
Some "Hand in homework" links broken

### ISSUE THREAD

**Issue by adamblanchard** [HackYourFuture-CPH/curriculum#79]
Saw this at least on git and node.js (all weeks).

Example: https://github.com/HackYourFuture-CPH/node.js/blob/main/week1/homework/readme.md
"this resource" page 404s.

**Comment by adamblanchard** [comment]
Looks like they should be replaced with [github.com/HackYourFuture-CPH/Git/blob/main/homework-submission.md](github.com/HackYourFuture-CPH/Git/blob/main/homework-submission.md)

**Comment by shpomp** [comment]
Only found it on node.js and fixed. Git does not have the link in homework readmes.
